'use client';

import { FormEvent, useEffect, useState } from 'react';
import { supabase } from '@/lib/supabase';

type Release = { id: string; version: string; status: string; notes_vi: string | null; created_at: string; verified_at: string | null; published_at: string | null; release_artifacts: Array<{ id: string; filename: string; size_bytes: number; sha256: string | null; signature_status: string }> | null };
type InitResponse = { releaseId: string; artifactId: string; uploadUrl: string };

export default function ReleaseManager() {
  const [releases, setReleases] = useState<Release[]>([]); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  async function load() { if (!supabase) return; const { data } = await supabase.from('software_releases').select('id,version,status,notes_vi,created_at,verified_at,published_at,release_artifacts(id,filename,size_bytes,sha256,signature_status)').order('created_at', { ascending: false }); setReleases((data as Release[] | null) ?? []); }
  useEffect(() => { queueMicrotask(() => void load()); }, []);
  async function upload(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!supabase) return; const form = new FormData(event.currentTarget); const file = form.get('installer'); if (!(file instanceof File) || !file.name.toLowerCase().endsWith('.exe')) { setMessage('Chỉ chấp nhận bộ cài .exe.'); return; }
    setBusy(true); setMessage('Đang tạo vùng upload an toàn…');
    const { data, error } = await supabase.functions.invoke<InitResponse>('release-upload-init', { body: { version: form.get('version'), filename: file.name, sizeBytes: file.size, notesVi: form.get('notesVi'), notesEn: form.get('notesEn') } });
    if (error || !data?.uploadUrl) { setBusy(false); setMessage('Không thể khởi tạo upload. Kiểm tra MFA và cấu hình R2.'); return; }
    const uploadResponse = await fetch(data.uploadUrl, { method: 'PUT', headers: { 'content-type': 'application/vnd.microsoft.portable-executable' }, body: file });
    if (!uploadResponse.ok) { setBusy(false); setMessage('Upload R2 thất bại.'); return; }
    const completed = await supabase.functions.invoke('release-upload-complete', { body: { releaseId: data.releaseId, artifactId: data.artifactId } });
    setBusy(false); setMessage(completed.error ? 'Đã upload nhưng chưa thể bắt đầu xác minh.' : 'Đã upload. Windows runner đang xác minh Authenticode và SHA-256.'); await load();
  }
  async function publish(releaseId: string) { if (!supabase) return; setBusy(true); const { error } = await supabase.functions.invoke('release-publish', { body: { releaseId } }); setBusy(false); setMessage(error ? 'Không thể publish. Release phải được xác minh hợp lệ.' : 'Release đã được công khai.'); await load(); }
  async function withdraw(releaseId: string) { if (!supabase || !window.confirm('Rút bản phát hành này khỏi trang tải xuống?')) return; setBusy(true); const { error } = await supabase.functions.invoke('release-publish', { body: { releaseId, action: 'withdraw' } }); setBusy(false); setMessage(error ? 'Không thể rút release.' : 'Release đã được rút khỏi trang tải xuống.'); await load(); }
  return <><form onSubmit={upload} className="rounded-lg border border-slate-200 bg-white p-6"><div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-semibold">Phiên bản<input required name="version" pattern="[0-9]+\.[0-9]+\.[0-9]+" placeholder="0.1.2" className="mt-2 w-full rounded-md border border-slate-300 px-3 py-2.5 font-normal" /></label><label className="text-sm font-semibold">Bộ cài đã ký<input required name="installer" type="file" accept=".exe,application/vnd.microsoft.portable-executable" className="mt-2 block w-full rounded-md border border-slate-300 px-3 py-2 text-sm font-normal" /></label><label className="text-sm font-semibold">Ghi chú tiếng Việt<textarea name="notesVi" rows={3} className="mt-2 w-full rounded-md border border-slate-300 px-3 py-2.5 font-normal" /></label><label className="text-sm font-semibold">English notes<textarea name="notesEn" rows={3} className="mt-2 w-full rounded-md border border-slate-300 px-3 py-2.5 font-normal" /></label></div><button disabled={busy} className="mt-5 rounded-md bg-slate-950 px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-60">{busy ? 'Đang xử lý…' : 'Upload bản nháp'}</button>{message && <p className="mt-4 text-sm text-slate-600">{message}</p>}</form><div className="mt-6 space-y-4">{releases.map((release) => { const artifact = release.release_artifacts?.[0]; return <article key={release.id} className="rounded-lg border border-slate-200 bg-white p-5"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><h2 className="font-semibold">nATime {release.version}</h2><p className="mt-1 text-sm text-slate-500">{artifact?.filename ?? 'Chưa có artifact'} · {release.status} · chữ ký: {artifact?.signature_status ?? '—'}</p>{artifact?.sha256 && <p className="mt-2 break-all font-mono text-xs text-slate-500">{artifact.sha256}</p>}</div><div className="flex gap-2">{release.status === 'verified' && <button onClick={() => void publish(release.id)} disabled={busy} className="h-fit rounded-md bg-blue-700 px-4 py-2 text-sm font-semibold text-white">Publish</button>}{release.status === 'published' && <button onClick={() => void withdraw(release.id)} disabled={busy} className="h-fit rounded-md border border-red-300 px-4 py-2 text-sm font-semibold text-red-700">Rút bản</button>}</div></div></article>; })}</div></>;
}
