import Link from 'next/link';
import type { ReactNode } from 'react';
import ContactForm from './ContactForm';
import MobilePreviewDownload from './MobilePreviewDownload';
import ProductPricing from './ProductPricing';
import ProductPreview from './ProductPreview';
import PublicShell from './PublicShell';
import ReleaseDownload from './ReleaseDownload';

type Locale = 'vi' | 'en';

function Intro({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) {
  return <section className="border-b border-slate-200 bg-slate-50"><div className="mx-auto max-w-[1200px] px-4 py-14 sm:px-6 lg:py-18"><p className="text-sm font-semibold text-blue-700">{eyebrow}</p><h1 className="mt-3 max-w-3xl text-4xl font-bold tracking-tight sm:text-5xl">{title}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-600">{description}</p></div></section>;
}

function VisualPageHero({ eyebrow, title, description, children }: { eyebrow: string; title: string; description: string; children: ReactNode }) {
  return <section className="relative overflow-hidden border-b border-slate-200 bg-[linear-gradient(135deg,#f8fafc,#eff6ff_55%,#ffffff)]"><div className="absolute -right-24 -top-36 h-96 w-96 rounded-full bg-blue-200/50 blur-3xl" aria-hidden="true" /><div className="relative mx-auto grid max-w-[1200px] items-center gap-10 px-4 py-14 sm:px-6 lg:grid-cols-[0.9fr_1.1fr] lg:py-20"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-blue-700">{eyebrow}</p><h1 className="mt-4 text-4xl font-black tracking-[-0.035em] text-slate-950 sm:text-5xl">{title}</h1><p className="mt-5 max-w-xl text-lg leading-8 text-slate-600">{description}</p></div><div>{children}</div></div></section>;
}

export function FeaturesContent({ locale }: { locale: Locale }) {
  const vi = locale === 'vi';
  const items = [
    { title: vi ? 'Chấm công' : 'Attendance', description: vi ? 'Quản lý dữ liệu chấm công, ca làm việc và kết quả tổng hợp theo nghiệp vụ được cấp phép.' : 'Manage attendance data, work shifts and calculated results within licensed capabilities.', kind: 'attendance' as const, points: vi ? ['Lọc theo ngày và đơn vị', 'Theo dõi giờ vào, giờ ra', 'Kết quả theo ca làm việc'] : ['Filter by date and unit', 'Review check-in and check-out', 'Shift-based results'] },
    { title: vi ? 'Thiết bị' : 'Devices', description: vi ? 'Khai báo máy chấm công, theo dõi kết nối và thực hiện các thao tác đồng bộ được hệ thống hỗ trợ.' : 'Register attendance devices, monitor connectivity and use supported synchronization operations.', kind: 'devices' as const, points: vi ? ['Trạng thái kết nối', 'Tác vụ đồng bộ hỗ trợ', 'Thiết bị theo phạm vi license'] : ['Connectivity status', 'Supported synchronization', 'Licensed device allowance'] },
    { title: vi ? 'Kiểm soát ra vào' : 'Access control', description: vi ? 'Module Access dành cho gói Professional và chỉ xuất hiện khi license cho phép.' : 'The Access module is available with Professional and only appears when licensed.', kind: 'overview' as const, points: vi ? ['Theo quyền được cấp', 'Ẩn module ngoài gói', 'Backend tiếp tục bảo vệ dữ liệu'] : ['Entitlement-aware access', 'Unlicensed modules hidden', 'Backend enforcement remains active'] },
  ];
  return <PublicShell locale={locale}><VisualPageHero eyebrow={vi ? 'Tính năng' : 'Features'} title={vi ? 'Nghiệp vụ thật, hiển thị đúng theo license' : 'Real operations, shown according to the license'} description={vi ? 'nATime chỉ giới thiệu những module đang có trong danh mục license hiện hành.' : 'nATime only advertises modules available in the current licensing catalog.'}><ProductPreview kind="overview" compact /></VisualPageHero><section className="mx-auto max-w-[1200px] space-y-20 px-4 py-20 sm:px-6">{items.map((item, index) => <article key={item.title} className="grid items-center gap-10 lg:grid-cols-2"><div className={index % 2 ? 'lg:order-2' : ''}><p className="text-xs font-black tracking-[0.18em] text-blue-700">0{index + 1}</p><h2 className="mt-4 text-3xl font-black tracking-tight">{item.title}</h2><p className="mt-4 max-w-xl leading-7 text-slate-600">{item.description}</p><ul className="mt-6 space-y-3">{item.points.map((point) => <li key={point} className="flex items-center gap-3 text-sm font-semibold text-slate-700"><span className="grid h-6 w-6 place-items-center rounded-full bg-blue-50 text-xs text-blue-700">✓</span>{point}</li>)}</ul></div><div className={index % 2 ? 'lg:order-1' : ''}><ProductPreview kind={item.kind} compact /></div></article>)}</section></PublicShell>;
}

export function PricingContent({ locale }: { locale: Locale }) {
  const vi = locale === 'vi';
  return <PublicShell locale={locale}><VisualPageHero eyebrow={vi ? 'Bảng giá' : 'Pricing'} title={vi ? 'Chọn gói theo quy mô sử dụng' : 'Choose a plan for your usage'} description={vi ? 'Standard và Professional thanh toán qua PayOS. Enterprise được khảo sát và báo giá riêng.' : 'Standard and Professional are paid through PayOS. Enterprise is assessed and quoted separately.'}><div className="rounded-2xl border border-blue-200 bg-white/90 p-7 shadow-xl shadow-blue-900/10"><p className="text-xs font-black uppercase tracking-[0.16em] text-blue-700">Standard trial</p><p className="mt-3 text-4xl font-black text-slate-950">7 {vi ? 'ngày' : 'days'}</p><div className="mt-5 grid grid-cols-2 gap-3 text-sm"><div className="rounded-lg bg-slate-50 p-3"><strong className="block text-lg">50</strong><span className="text-slate-500">{vi ? 'nhân sự' : 'employees'}</span></div><div className="rounded-lg bg-slate-50 p-3"><strong className="block text-lg">1</strong><span className="text-slate-500">{vi ? 'thiết bị' : 'device'}</span></div></div></div></VisualPageHero><section className="mx-auto max-w-[1200px] px-4 py-20 sm:px-6"><ProductPricing locale={locale} /><div className="mt-12 flex flex-col justify-between gap-5 rounded-2xl border border-blue-200 bg-blue-50 p-7 sm:flex-row sm:items-center"><div><h2 className="font-bold text-blue-950">{vi ? 'Dùng thử trước khi mua' : 'Try before buying'}</h2><p className="mt-2 text-sm leading-6 text-blue-900">{vi ? 'Mỗi tài khoản và Hardware ID đủ điều kiện chỉ nhận trial Standard một lần.' : 'Each eligible account and Hardware ID can receive one Standard trial.'}</p></div><Link href="/register?trial=standard" className="shrink-0 rounded-lg bg-blue-700 px-5 py-3 text-center text-sm font-bold text-white hover:bg-blue-800">{vi ? 'Bắt đầu trial' : 'Start trial'}</Link></div></section></PublicShell>;
}

export function DownloadContent({ locale }: { locale: Locale }) {
  const vi = locale === 'vi';
  const checks = vi ? [['01', 'Authenticode', 'Bộ cài phải có chữ ký hợp lệ.'], ['02', 'SHA-256', 'Mã băm được công bố cùng release.'], ['03', 'Published', 'Chỉ release đã xác minh mới xuất hiện.']] : [['01', 'Authenticode', 'The installer must have a valid signature.'], ['02', 'SHA-256', 'The hash is published with the release.'], ['03', 'Published', 'Only verified releases are listed.']];
  return <PublicShell locale={locale}><VisualPageHero eyebrow="Windows x64" title={vi ? 'Tải bộ cài nATime đã xác minh' : 'Download a verified nATime installer'} description={vi ? 'Bộ cài đi qua vùng cách ly, Windows runner và bước kiểm tra chữ ký trước khi được công khai.' : 'The installer passes through quarantine, a Windows runner and signature verification before publication.'}><div className="space-y-3">{checks.map(([number, title, text]) => <div key={number} className="flex gap-4 rounded-xl border border-slate-200 bg-white/90 p-4 shadow-sm"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-blue-50 text-xs font-black text-blue-700">{number}</span><div><p className="font-bold">{title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{text}</p></div></div>)}</div></VisualPageHero><section className="mx-auto max-w-[900px] px-4 py-20 sm:px-6"><ReleaseDownload locale={locale} /><MobilePreviewDownload locale={locale} /><div className="mt-8 rounded-xl border border-slate-200 bg-slate-50 p-6"><h2 className="font-bold">{vi ? 'Trước khi cài đặt' : 'Before installation'}</h2><ul className="mt-4 space-y-3 text-sm leading-6 text-slate-600"><li>✓ {vi ? 'Đối chiếu chữ ký số và SHA-256 được công bố.' : 'Compare the published digital signature and SHA-256.'}</li><li>✓ {vi ? 'Dùng tài khoản nATime để nhận trial hoặc mua license.' : 'Use your nATime account for a trial or paid license.'}</li><li>✓ {vi ? 'Bộ cài Windows dùng cho máy chủ; APK Android chỉ cài trên điện thoại thử nghiệm.' : 'Use the Windows installer for the server; install the Android APK only on a test phone.'}</li></ul></div></section></PublicShell>;
}

export function DocsContent({ locale }: { locale: Locale }) {
  const vi = locale === 'vi';
  const steps = vi ? [
    ['1. Tải bộ cài', 'Tải phiên bản Windows đang được phát hành tại trang Tải xuống và kiểm tra SHA-256.'],
    ['2. Cài đặt', 'Chạy bộ cài bằng quyền phù hợp và chờ hoàn tất cấu hình dịch vụ nATime.'],
    ['3. Mở hệ thống', 'Truy cập địa chỉ cục bộ do bộ cài cung cấp và đăng nhập tài khoản quản trị của hệ thống.'],
    ['4. Kích hoạt', 'Mở Cài đặt → Bản quyền, tạo mã liên kết rồi phê duyệt bằng tài khoản tại Cổng khách hàng.'],
    ['5. Xác minh', 'Tải lại trạng thái bản quyền, kiểm tra gói, hạn dùng, Hardware ID và module được cấp phép.'],
  ] : [
    ['1. Download', 'Download the current Windows release and verify its SHA-256.'],
    ['2. Install', 'Run the installer with the appropriate permissions and wait for nATime services to be configured.'],
    ['3. Open nATime', 'Open the local address provided by the installer and sign in to the system administrator account.'],
    ['4. Activate', 'Open Settings → License, create a link code and approve it from the customer portal.'],
    ['5. Verify', 'Reload the license status and verify the plan, expiry, Hardware ID and licensed modules.'],
  ];
  return <PublicShell locale={locale}><VisualPageHero eyebrow={vi ? 'Tài liệu' : 'Documentation'} title={vi ? 'Cài đặt và kích hoạt theo từng bước' : 'Install and activate step by step'} description={vi ? 'Quy trình dưới đây bám theo bộ cài Windows và hệ thống license đang hoạt động.' : 'This flow follows the current Windows installer and licensing system.'}><div className="grid grid-cols-5 gap-2">{steps.map(([title], index) => <div key={title} className="rounded-xl border border-slate-200 bg-white p-3 text-center shadow-sm"><span className="mx-auto grid h-8 w-8 place-items-center rounded-full bg-blue-700 text-xs font-black text-white">{index + 1}</span><p className="mt-2 hidden truncate text-[10px] font-bold text-slate-600 sm:block">{title.replace(/^\d+\.\s*/, '')}</p></div>)}</div></VisualPageHero><section className="mx-auto max-w-[900px] px-4 py-20 sm:px-6"><div className="relative space-y-4 before:absolute before:bottom-8 before:left-[27px] before:top-8 before:w-px before:bg-blue-100">{steps.map(([title, text], index) => <article key={title} className="relative grid grid-cols-[56px_1fr] gap-4 rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><span className="relative z-10 grid h-11 w-11 place-items-center rounded-xl bg-blue-50 text-sm font-black text-blue-700">{index + 1}</span><div><h2 className="text-lg font-bold">{title.replace(/^\d+\.\s*/, '')}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></div></article>)}</div><div className="mt-8 rounded-xl bg-slate-950 p-6 text-sm text-slate-300"><p className="font-bold text-white">{vi ? 'Cần hỗ trợ?' : 'Need help?'}</p><p className="mt-2">{vi ? 'Gửi mô tả lỗi và log cài đặt đã loại bỏ secret tới ' : 'Send the issue description and a sanitized installation log to '}<a className="text-white underline" href="mailto:support@natime.vn">support@natime.vn</a>.</p></div></section></PublicShell>;
}

export function AboutContent({ locale }: { locale: Locale }) {
  const vi = locale === 'vi';
  return <PublicShell locale={locale}><Intro eyebrow={vi ? 'Giới thiệu' : 'About'} title={vi ? 'Phần mềm tập trung vào vận hành thực tế' : 'Software focused on real operations'} description={vi ? 'nATime được phát triển cho nhu cầu chấm công và quản lý thiết bị của doanh nghiệp.' : 'nATime is built for business attendance and device management needs.'} /><section className="mx-auto grid max-w-[1000px] gap-8 px-4 py-16 sm:px-6 md:grid-cols-2"><article className="rounded-xl border border-slate-200 p-7"><h2 className="text-xl font-semibold">{vi ? 'Nguyên tắc sản phẩm' : 'Product principle'}</h2><p className="mt-4 leading-7 text-slate-600">{vi ? 'Chỉ công bố tính năng đã được phê duyệt, kiểm thử và có cơ chế cấp phép rõ ràng.' : 'Only approved, tested capabilities with clear licensing are published.'}</p></article><article className="rounded-xl border border-slate-200 p-7"><h2 className="text-xl font-semibold">{vi ? 'Mô hình triển khai' : 'Deployment model'}</h2><p className="mt-4 leading-7 text-slate-600">{vi ? 'Ứng dụng được cài trên Windows của khách hàng; tài khoản natime.vn dùng để mua và quản lý bản quyền.' : 'The application is installed on the customer’s Windows machine; natime.vn accounts are used to buy and manage licenses.'}</p></article></section></PublicShell>;
}

export function ChangelogContent({ locale }: { locale: Locale }) {
  const vi = locale === 'vi';
  return <PublicShell locale={locale}><Intro eyebrow={vi ? 'Nhật ký thay đổi' : 'Changelog'} title={vi ? 'Các phiên bản đã phát hành' : 'Published releases'} description={vi ? 'Danh sách chỉ lấy từ những release Windows đã được xác minh và công khai.' : 'This list only contains verified and published Windows releases.'} /><section className="mx-auto max-w-[900px] px-4 py-16 sm:px-6"><ReleaseDownload locale={locale} changelog /></section></PublicShell>;
}

export function ContactContent({ locale }: { locale: Locale }) {
  const vi = locale === 'vi';
  return <PublicShell locale={locale}><Intro eyebrow={vi ? 'Liên hệ' : 'Contact'} title={vi ? 'Trao đổi với nATime' : 'Talk to nATime'} description={vi ? 'Gửi yêu cầu Enterprise, câu hỏi trước khi mua hoặc vấn đề của khách hàng hiện tại.' : 'Send an Enterprise inquiry, pre-sales question or existing customer issue.'} /><section className="mx-auto grid max-w-[1000px] gap-10 px-4 py-16 sm:px-6 lg:grid-cols-[0.7fr_1.3fr]"><div><h2 className="text-xl font-semibold">{vi ? 'Kênh liên hệ' : 'Contact channel'}</h2><p className="mt-4 text-sm leading-6 text-slate-600">{vi ? 'Form được lưu để theo dõi trạng thái xử lý. Không gửi mật khẩu, private key hoặc dữ liệu sinh trắc học.' : 'The form is retained for follow-up. Do not send passwords, private keys or biometric data.'}</p><a href="mailto:support@natime.vn" className="mt-5 inline-block text-sm font-semibold text-blue-700 hover:underline">support@natime.vn</a></div><ContactForm locale={locale} /></section></PublicShell>;
}

export type PolicyKind = 'privacy' | 'terms' | 'payment' | 'refund';
export function PolicyContent({ locale, kind }: { locale: Locale; kind: PolicyKind }) {
  const vi = locale === 'vi';
  const privacyContent = {
    title: vi ? 'Chính sách quyền riêng tư' : 'Privacy policy',
    lead: vi
      ? 'Cách nATime xử lý dữ liệu trên natime.vn và trong ứng dụng Mobile kết nối WebPortal self-host.'
      : 'How nATime handles data on natime.vn and in the Mobile app connected to a self-hosted WebPortal.',
    sections: vi
      ? [
          ['Phạm vi dữ liệu trên natime.vn', 'natime.vn xử lý thông tin tài khoản khách hàng, đơn vị, đơn hàng, trạng thái license, Hardware ID dạng băm và dữ liệu kỹ thuật cần thiết để xác thực, thanh toán, cấp phép, hỗ trợ và bảo vệ dịch vụ.'],
          ['Dữ liệu WebPortal self-host', 'nATime Mobile kết nối trực tiếp tới URL WebPortal do doanh nghiệp cung cấp. Theo cấu hình mặc định, dữ liệu nhân sự, lịch làm việc, chấm công và tài sản trong hệ thống self-host không được chuyển về natime.vn.'],
          ['Tài khoản Mobile', 'Tài khoản đăng nhập do quản trị viên của doanh nghiệp tạo và quản lý trong WebPortal. Mobile không tạo, xóa hoặc khóa tài khoản. Khi cần cấp tài khoản, đổi mật khẩu, khóa tài khoản hoặc xử lý dữ liệu nhân sự, người dùng liên hệ quản trị viên của doanh nghiệp.'],
          ['Dữ liệu lưu trên điện thoại', 'Mobile lưu URL WebPortal và phiên đăng nhập cần thiết để duy trì kết nối. Access token và refresh token được bảo vệ bằng Android Keystore; mật khẩu không được lưu. Đăng xuất sẽ xóa dữ liệu phiên trên điện thoại nhưng không xóa tài khoản hay hồ sơ tại WebPortal.'],
          ['Camera và mã QR', 'Quyền Camera chỉ được yêu cầu khi người dùng mở chức năng quét QR tài sản. Luồng này dùng hình ảnh camera để nhận mã QR trên thiết bị và không chủ động tải ảnh chụp lên natime.vn.'],
          ['Kết nối mạng', 'Nên sử dụng HTTPS. Mobile chỉ cho phép HTTP với địa chỉ IPv4 LAN riêng và hiển thị cảnh báo vì thông tin đăng nhập, dữ liệu truyền qua HTTP không được TLS mã hóa.'],
          ['Lưu giữ và liên hệ', 'Doanh nghiệp vận hành WebPortal quyết định việc lưu giữ hồ sơ nhân sự và chấm công trong hệ thống self-host. Yêu cầu liên quan dữ liệu WebPortal cần gửi cho quản trị viên doanh nghiệp; yêu cầu liên quan tài khoản, đơn hàng hoặc license trên natime.vn gửi tới support@natime.vn.'],
        ]
      : [
          ['Data on natime.vn', 'natime.vn processes customer account, organization, order, license status, hashed Hardware ID and technical data required for authentication, payment, licensing, support and service protection.'],
          ['Self-hosted WebPortal data', 'nATime Mobile connects directly to the WebPortal URL supplied by the organization. By default, personnel, schedule, attendance and asset data in the self-hosted system is not sent to natime.vn.'],
          ['Mobile accounts', 'Sign-in accounts are created and managed by the organization administrator in WebPortal. Mobile does not create, delete or lock accounts. Users contact their organization administrator for account provisioning, password changes, account suspension or employee-record requests.'],
          ['Data stored on the phone', 'Mobile stores the WebPortal URL and session data required to maintain the connection. Access and refresh tokens are protected by Android Keystore; the password is not stored. Signing out removes the local session but does not delete the WebPortal account or employee record.'],
          ['Camera and QR codes', 'Camera permission is requested only when the user opens the asset QR scanner. The camera image is used to recognize the QR code on-device and this flow does not intentionally upload captured photos to natime.vn.'],
          ['Network connection', 'HTTPS is recommended. Mobile permits HTTP only for private LAN IPv4 addresses and displays a warning because credentials and data sent over HTTP are not protected by TLS.'],
          ['Retention and contact', 'The organization operating WebPortal controls retention of personnel and attendance records in its self-hosted system. WebPortal data requests should be sent to the organization administrator; requests about natime.vn accounts, orders or licenses can be sent to support@natime.vn.'],
        ],
  };
  const policyContent = {
    privacy: { title: vi ? 'Chính sách quyền riêng tư' : 'Privacy policy', lead: vi ? 'Cách nATime xử lý dữ liệu tài khoản và bản quyền.' : 'How nATime handles account and licensing data.', sections: vi ? [['Dữ liệu thu thập', 'Thông tin tài khoản, đơn vị, đơn hàng, trạng thái license, Hardware ID dạng băm và dữ liệu kỹ thuật cần thiết để vận hành dịch vụ.'], ['Mục đích sử dụng', 'Xác thực, thanh toán, cấp phép, hỗ trợ và bảo vệ hệ thống. nATime không yêu cầu gửi mẫu sinh trắc học qua website.'], ['Liên hệ', 'Yêu cầu về dữ liệu cá nhân được gửi tới support@natime.vn.']] : [['Data collected', 'Account, company, order, license status, hashed Hardware ID and technical data required to operate the service.'], ['Use', 'Authentication, payment, licensing, support and system protection. nATime does not ask users to upload biometric samples through this website.'], ['Contact', 'Privacy requests can be sent to support@natime.vn.']] },
    terms: { title: vi ? 'Điều khoản sử dụng' : 'Terms of use', lead: vi ? 'Điều kiện sử dụng website, tài khoản và license nATime.' : 'Conditions for using the nATime website, account and licenses.', sections: vi ? [['Tài khoản', 'Người dùng chịu trách nhiệm bảo vệ thông tin đăng nhập và cung cấp thông tin chính xác.'], ['License', 'Quyền sử dụng phụ thuộc gói, thời hạn, module và số thiết bị được cấp. Không được can thiệp hoặc vượt qua cơ chế cấp phép.'], ['Giới hạn', 'Các nội dung chưa được xác nhận bằng hợp đồng hoặc báo giá không tạo thành cam kết dịch vụ riêng.']] : [['Account', 'Users are responsible for protecting credentials and providing accurate information.'], ['License', 'Usage rights depend on the purchased plan, term, modules and device limit. The licensing mechanism may not be bypassed.'], ['Limitations', 'Content not confirmed in a contract or quotation does not create a separate service commitment.']] },
    payment: { title: vi ? 'Chính sách thanh toán và giao nhận số' : 'Payment and digital delivery policy', lead: vi ? 'Quy trình thanh toán PayOS và cấp quyền sử dụng phần mềm.' : 'PayOS payment and digital software delivery flow.', sections: vi ? [['Thanh toán', 'Standard và Professional được thanh toán qua liên kết PayOS. Webhook hợp lệ là nguồn xác nhận thanh toán.'], ['Giao nhận', 'Sau khi xác nhận, entitlement được cập nhật trong Cổng khách hàng. Bộ cài Windows được tải riêng tại trang Tải xuống.'], ['Hóa đơn', 'Website ghi nhận yêu cầu hóa đơn nhưng không cam kết tự động phát hành hóa đơn GTGT.']] : [['Payment', 'Standard and Professional are paid through a PayOS payment link. A valid webhook is the source of payment confirmation.'], ['Delivery', 'After confirmation, the entitlement is updated in the customer portal. The Windows installer is downloaded separately.'], ['Invoice', 'The website records invoice requests but does not promise automatic VAT invoice issuance.']] },
    refund: { title: vi ? 'Chính sách hoàn tiền' : 'Refund policy', lead: vi ? 'Cách tiếp nhận và đánh giá yêu cầu hoàn tiền.' : 'How refund requests are received and assessed.', sections: vi ? [['Gửi yêu cầu', 'Khách hàng gửi mã đơn hàng và lý do tới support@natime.vn. Không gửi thông tin ngân hàng nhạy cảm qua form công khai.'], ['Xử lý', 'Yêu cầu được xem xét theo trạng thái kích hoạt, thời gian sử dụng và thỏa thuận tại thời điểm mua.'], ['Kết quả', 'nATime thông báo kết quả và phương thức xử lý qua email đã đăng ký; website không cam kết mọi yêu cầu đều được chấp thuận.']] : [['Request', 'Send the order reference and reason to support@natime.vn. Do not send sensitive bank information through the public form.'], ['Assessment', 'Requests are assessed based on activation status, usage period and the agreement at purchase.'], ['Outcome', 'nATime communicates the outcome to the registered email; not every request is guaranteed approval.']] },
  }[kind];
  const content = kind === 'privacy' ? privacyContent : policyContent;
  return <PublicShell locale={locale}><Intro eyebrow={vi ? 'Chính sách' : 'Policy'} title={content.title} description={content.lead} /><section className="mx-auto max-w-[850px] px-4 py-16 sm:px-6"><p className="mb-8 text-sm text-slate-500">{vi ? 'Cập nhật: 15/07/2026. Nội dung cần được chủ sở hữu duyệt trước khi áp dụng chính thức.' : 'Updated: 15 July 2026. This content requires owner approval before it becomes effective.'}</p><div className="space-y-8">{content.sections.map(([title, text]) => <section key={title}><h2 className="text-xl font-semibold">{title}</h2><p className="mt-3 leading-7 text-slate-600">{text}</p></section>)}</div></section></PublicShell>;
}
